"""
CareerCompass - Curated Career Knowledge Base
================================================
Structured in the spirit of O*NET (RIASEC interest model, work-context/skill
profiles) and aligned to South African NSC subjects, APS admission scoring,
and SETA sector categories, since no single public dataset combines all of
these for the SA youth-guidance context. Each career record is hand-curated
from O*NET occupational summaries, CareerHelp/CareerJunction SA salary
benchmarks, and DHET/SETA sector lists.

RIASEC = Holland Code interest dimensions:
  R = Realistic, I = Investigative, A = Artistic,
  S = Social, E = Enterprising, C = Conventional
Personality dimensions use the Big Five (OCEAN), scored 0-1 as the IDEAL
profile for someone thriving in that career.
"""

CAREERS = [
    # ---------------- HEALTH ----------------
    dict(name="Medical Doctor", sector="Health", seta="HWSETA",
         riasec=dict(R=0.3, I=0.9, A=0.1, S=0.8, E=0.3, C=0.4),
         personality=dict(openness=0.6, conscientiousness=0.9, extraversion=0.5, agreeableness=0.7, neuroticism=0.2),
         subjects={"Mathematics": 70, "Physical Sciences": 70, "Life Sciences": 70, "English": 60},
         min_aps=38, duration_years=6, budget_level=3, salary_entry=420000, growth_outlook="High",
         description="Diagnose and treat illness; requires an MBChB degree and community service year.",
         next_steps=["Achieve 70%+ in Maths, Physical Sciences and Life Sciences",
                      "Apply to MBChB programmes (Wits, UCT, UP, UKZN, Stellenbosch, SMU)",
                      "Look into HPCSA and NSFAS/HWSETA bursaries for medicine"]),
    dict(name="Professional Nurse", sector="Health", seta="HWSETA",
         riasec=dict(R=0.3, I=0.5, A=0.1, S=0.9, E=0.2, C=0.4),
         personality=dict(openness=0.4, conscientiousness=0.8, extraversion=0.6, agreeableness=0.9, neuroticism=0.2),
         subjects={"Mathematics": 50, "Life Sciences": 60, "English": 55},
         min_aps=26, duration_years=4, budget_level=2, salary_entry=250000, growth_outlook="High",
         description="Provide patient care in hospitals, clinics and communities.",
         next_steps=["Aim for 60%+ Life Sciences", "Apply to nursing colleges or university B.Cur programmes",
                      "Check SANC registration requirements and NSFAS funding"]),
    dict(name="Pharmacist", sector="Health", seta="HWSETA",
         riasec=dict(R=0.2, I=0.85, A=0.1, S=0.5, E=0.3, C=0.6),
         personality=dict(openness=0.5, conscientiousness=0.9, extraversion=0.4, agreeableness=0.6, neuroticism=0.2),
         subjects={"Mathematics": 65, "Physical Sciences": 65, "Life Sciences": 60},
         min_aps=32, duration_years=4, budget_level=3, salary_entry=350000, growth_outlook="Medium",
         description="Dispense medication and advise on drug therapy.",
         next_steps=["Target 65%+ in Maths and Physical Sciences", "Apply for B.Pharm at Rhodes, Wits, UWC, TUT",
                      "Register as an intern with SAPC after graduating"]),
    dict(name="Physiotherapist", sector="Health", seta="HWSETA",
         riasec=dict(R=0.6, I=0.6, A=0.2, S=0.8, E=0.2, C=0.3),
         personality=dict(openness=0.5, conscientiousness=0.8, extraversion=0.6, agreeableness=0.8, neuroticism=0.2),
         subjects={"Mathematics": 60, "Physical Sciences": 55, "Life Sciences": 60},
         min_aps=30, duration_years=4, budget_level=3, salary_entry=280000, growth_outlook="Medium",
         description="Help patients recover movement and manage pain through physical therapy.",
         next_steps=["Keep Life Sciences and Physical Sciences above 55%",
                      "Apply to Wits, UCT, UP, UWC physiotherapy programmes"]),
    dict(name="Emergency Medical Technician (Paramedic)", sector="Health", seta="HWSETA",
         riasec=dict(R=0.7, I=0.5, A=0.1, S=0.7, E=0.3, C=0.3),
         personality=dict(openness=0.4, conscientiousness=0.8, extraversion=0.6, agreeableness=0.7, neuroticism=0.2),
         subjects={"Mathematics": 45, "Life Sciences": 50, "English": 50},
         min_aps=20, duration_years=2, budget_level=1, salary_entry=180000, growth_outlook="Medium",
         description="Provide emergency medical care and transport for patients.",
         next_steps=["Complete a Higher Certificate/Diploma in Emergency Medical Care",
                      "Register with the HPCSA", "Look at TVET college EMS programmes"]),

    # ---------------- ENGINEERING & TECH ----------------
    dict(name="Civil Engineer", sector="Engineering", seta="CETA",
         riasec=dict(R=0.8, I=0.8, A=0.2, S=0.2, E=0.4, C=0.5),
         personality=dict(openness=0.5, conscientiousness=0.8, extraversion=0.3, agreeableness=0.4, neuroticism=0.2),
         subjects={"Mathematics": 70, "Physical Sciences": 65},
         min_aps=34, duration_years=4, budget_level=3, salary_entry=340000, growth_outlook="High",
         description="Design and oversee construction of infrastructure like roads, bridges and buildings.",
         next_steps=["Push Maths and Physical Sciences above 65%",
                      "Apply to BEng/BSc Civil Engineering programmes",
                      "Explore CETA/ECSA-linked bursaries"]),
    dict(name="Electrical Engineer", sector="Engineering", seta="merSETA",
         riasec=dict(R=0.8, I=0.85, A=0.15, S=0.2, E=0.35, C=0.5),
         personality=dict(openness=0.55, conscientiousness=0.8, extraversion=0.3, agreeableness=0.4, neuroticism=0.2),
         subjects={"Mathematics": 75, "Physical Sciences": 70},
         min_aps=36, duration_years=4, budget_level=3, salary_entry=360000, growth_outlook="High",
         description="Design electrical systems, power grids and electronics.",
         next_steps=["Target 70%+ Maths and Physical Sciences", "Apply to BEng Electrical Engineering",
                      "Look at Eskom, Transnet and merSETA bursaries"]),
    dict(name="Mechanical Engineer", sector="Engineering", seta="merSETA",
         riasec=dict(R=0.85, I=0.8, A=0.15, S=0.15, E=0.3, C=0.45),
         personality=dict(openness=0.5, conscientiousness=0.8, extraversion=0.3, agreeableness=0.4, neuroticism=0.2),
         subjects={"Mathematics": 75, "Physical Sciences": 70},
         min_aps=36, duration_years=4, budget_level=3, salary_entry=360000, growth_outlook="Medium",
         description="Design and build machinery, engines and mechanical systems.",
         next_steps=["Maintain 70%+ Maths/Physical Sciences", "Apply to BEng Mechanical Engineering programmes"]),
    dict(name="Software Developer", sector="ICT", seta="MICT SETA",
         riasec=dict(R=0.4, I=0.85, A=0.4, S=0.2, E=0.3, C=0.55),
         personality=dict(openness=0.6, conscientiousness=0.7, extraversion=0.3, agreeableness=0.4, neuroticism=0.25),
         subjects={"Mathematics": 60, "English": 55},
         min_aps=26, duration_years=3, budget_level=2, salary_entry=300000, growth_outlook="High",
         description="Build software applications, websites and systems.",
         next_steps=["Build Maths to 60%+; start free coding courses (HarvardX CS50, freeCodeCamp)",
                      "Apply to BSc Computer Science / IT diplomas, or bootcamps like WeThinkCode_ / CodeSpace",
                      "Build a portfolio on GitHub"]),
    dict(name="Data Scientist / Analyst", sector="ICT", seta="MICT SETA",
         riasec=dict(R=0.2, I=0.9, A=0.3, S=0.2, E=0.4, C=0.65),
         personality=dict(openness=0.65, conscientiousness=0.75, extraversion=0.3, agreeableness=0.4, neuroticism=0.25),
         subjects={"Mathematics": 70, "English": 55},
         min_aps=30, duration_years=3, budget_level=2, salary_entry=320000, growth_outlook="High",
         description="Extract insights from data to guide business decisions using statistics and ML.",
         next_steps=["Push Maths above 70%", "Study BSc Data Science / Statistics / Computer Science",
                      "Practise with free courses (Kaggle Learn, Coursera)"]),
    dict(name="Network / IT Support Technician", sector="ICT", seta="MICT SETA",
         riasec=dict(R=0.6, I=0.6, A=0.1, S=0.3, E=0.3, C=0.6),
         personality=dict(openness=0.4, conscientiousness=0.7, extraversion=0.4, agreeableness=0.5, neuroticism=0.25),
         subjects={"Mathematics": 45, "English": 50},
         min_aps=18, duration_years=1, budget_level=1, salary_entry=160000, growth_outlook="Medium",
         description="Install, maintain and troubleshoot computer networks and hardware.",
         next_steps=["Complete A+/N+ certifications or a TVET IT diploma",
                      "Look at MICT SETA learnerships"]),
    dict(name="Cybersecurity Analyst", sector="ICT", seta="MICT SETA",
         riasec=dict(R=0.4, I=0.85, A=0.2, S=0.2, E=0.3, C=0.65),
         personality=dict(openness=0.55, conscientiousness=0.8, extraversion=0.25, agreeableness=0.4, neuroticism=0.25),
         subjects={"Mathematics": 60, "English": 55},
         min_aps=26, duration_years=3, budget_level=2, salary_entry=310000, growth_outlook="High",
         description="Protect organisations from cyberattacks and data breaches.",
         next_steps=["Study BSc IT/Computer Science with a security focus",
                      "Pursue CompTIA Security+ certification"]),
    dict(name="Artisan Electrician", sector="Trades", seta="merSETA",
         riasec=dict(R=0.9, I=0.4, A=0.1, S=0.2, E=0.2, C=0.4),
         personality=dict(openness=0.35, conscientiousness=0.75, extraversion=0.35, agreeableness=0.5, neuroticism=0.2),
         subjects={"Mathematics": 45, "Physical Sciences": 40},
         min_aps=15, duration_years=3, budget_level=1, salary_entry=170000, growth_outlook="High",
         description="Install and maintain electrical wiring and systems as a qualified trade.",
         next_steps=["Enrol in a TVET N-course or apprenticeship in electrical trade",
                      "Complete a trade test to become a qualified artisan (merSETA)"]),
    dict(name="Artisan - Plumber", sector="Trades", seta="CETA",
         riasec=dict(R=0.9, I=0.3, A=0.1, S=0.2, E=0.25, C=0.35),
         personality=dict(openness=0.3, conscientiousness=0.7, extraversion=0.35, agreeableness=0.5, neuroticism=0.2),
         subjects={"Mathematics": 40},
         min_aps=14, duration_years=3, budget_level=1, salary_entry=150000, growth_outlook="Medium",
         description="Install and repair piping and water systems as a qualified trade.",
         next_steps=["Enrol at a TVET college for plumbing", "Complete an apprenticeship and trade test"]),
    dict(name="Motor Mechanic / Auto Technician", sector="Trades", seta="merSETA",
         riasec=dict(R=0.9, I=0.45, A=0.1, S=0.15, E=0.2, C=0.35),
         personality=dict(openness=0.3, conscientiousness=0.7, extraversion=0.35, agreeableness=0.45, neuroticism=0.2),
         subjects={"Mathematics": 40, "Physical Sciences": 40},
         min_aps=14, duration_years=3, budget_level=1, salary_entry=150000, growth_outlook="Medium",
         description="Diagnose and repair vehicles as a qualified automotive trade.",
         next_steps=["Enrol in a TVET automotive repair programme or dealership apprenticeship"]),

    # ---------------- BUSINESS & FINANCE ----------------
    dict(name="Chartered Accountant (CA)", sector="Finance", seta="FASSET",
         riasec=dict(R=0.1, I=0.6, A=0.1, S=0.2, E=0.5, C=0.9),
         personality=dict(openness=0.4, conscientiousness=0.9, extraversion=0.35, agreeableness=0.4, neuroticism=0.2),
         subjects={"Mathematics": 70, "Accounting": 70, "English": 55},
         min_aps=32, duration_years=4, budget_level=2, salary_entry=330000, growth_outlook="High",
         description="Audit, tax and financial management professional (SAICA-registered).",
         next_steps=["Keep Maths and Accounting above 70%", "Study a SAICA-accredited BCom Accounting degree",
                      "Explore FASSET/Big-4 bursary programmes"]),
    dict(name="Financial Advisor / Planner", sector="Finance", seta="INSETA",
         riasec=dict(R=0.1, I=0.5, A=0.1, S=0.55, E=0.7, C=0.65),
         personality=dict(openness=0.4, conscientiousness=0.75, extraversion=0.65, agreeableness=0.55, neuroticism=0.25),
         subjects={"Mathematics": 55, "English": 55},
         min_aps=24, duration_years=3, budget_level=2, salary_entry=220000, growth_outlook="Medium",
         description="Advise clients on investments, insurance and retirement planning.",
         next_steps=["Study BCom Finance/Investment Management", "Pursue CFP certification via FPI"]),
    dict(name="Actuary", sector="Finance", seta="INSETA",
         riasec=dict(R=0.1, I=0.9, A=0.1, S=0.15, E=0.3, C=0.85),
         personality=dict(openness=0.5, conscientiousness=0.9, extraversion=0.25, agreeableness=0.35, neuroticism=0.2),
         subjects={"Mathematics": 85, "English": 55},
         min_aps=40, duration_years=4, budget_level=3, salary_entry=380000, growth_outlook="High",
         description="Use maths and statistics to assess financial risk for insurers/pension funds.",
         next_steps=["Push Maths above 85%", "Study BSc/BCom Actuarial Science (UCT, Wits, UP, UFS)",
                      "Begin ASSA actuarial exams while studying"]),
    dict(name="Marketing Manager", sector="Business", seta="FASSET",
         riasec=dict(R=0.1, I=0.4, A=0.6, S=0.5, E=0.85, C=0.4),
         personality=dict(openness=0.7, conscientiousness=0.6, extraversion=0.75, agreeableness=0.55, neuroticism=0.3),
         subjects={"Mathematics": 50, "English": 60},
         min_aps=24, duration_years=3, budget_level=2, salary_entry=260000, growth_outlook="Medium",
         description="Plan and execute campaigns to promote products/brands.",
         next_steps=["Study BCom Marketing or Communications", "Build a portfolio with social-media/campaign projects"]),
    dict(name="Human Resources Manager", sector="Business", seta="Services SETA",
         riasec=dict(R=0.1, I=0.35, A=0.2, S=0.8, E=0.6, C=0.55),
         personality=dict(openness=0.5, conscientiousness=0.75, extraversion=0.6, agreeableness=0.75, neuroticism=0.25),
         subjects={"Mathematics": 45, "English": 60},
         min_aps=22, duration_years=3, budget_level=2, salary_entry=250000, growth_outlook="Medium",
         description="Manage recruitment, employee relations and workplace policy.",
         next_steps=["Study BCom/BA Human Resource Management", "Join SABPP for professional registration"]),
    dict(name="Entrepreneur / Small Business Owner", sector="Business", seta="Services SETA",
         riasec=dict(R=0.4, I=0.5, A=0.4, S=0.4, E=0.9, C=0.4),
         personality=dict(openness=0.75, conscientiousness=0.65, extraversion=0.75, agreeableness=0.45, neuroticism=0.3),
         subjects={"Mathematics": 45, "English": 50},
         min_aps=16, duration_years=1, budget_level=1, salary_entry=0, growth_outlook="Variable",
         description="Start and run your own business or venture.",
         next_steps=["Take a short course in small-business management (SEDA, SAB Foundation)",
                      "Explore NYDA youth business grants and mentorship programmes"]),
    dict(name="Logistics / Supply Chain Manager", sector="Business", seta="TETA",
         riasec=dict(R=0.4, I=0.55, A=0.1, S=0.3, E=0.65, C=0.65),
         personality=dict(openness=0.45, conscientiousness=0.8, extraversion=0.5, agreeableness=0.45, neuroticism=0.25),
         subjects={"Mathematics": 55, "English": 50},
         min_aps=22, duration_years=3, budget_level=2, salary_entry=240000, growth_outlook="High",
         description="Coordinate the movement of goods from suppliers to customers.",
         next_steps=["Study BCom/Diploma in Logistics or Supply Chain Management",
                      "Look at TETA learnerships"]),
    dict(name="Retail / Sales Manager", sector="Business", seta="W&RSETA",
         riasec=dict(R=0.2, I=0.3, A=0.2, S=0.5, E=0.8, C=0.45),
         personality=dict(openness=0.5, conscientiousness=0.65, extraversion=0.8, agreeableness=0.55, neuroticism=0.3),
         subjects={"Mathematics": 45, "English": 50},
         min_aps=18, duration_years=2, budget_level=1, salary_entry=180000, growth_outlook="Medium",
         description="Manage retail store operations, staff and sales targets.",
         next_steps=["Consider W&RSETA learnerships", "Study a Diploma in Retail Business Management"]),

    # ---------------- EDUCATION & SOCIAL SERVICES ----------------
    dict(name="Foundation Phase Teacher", sector="Education", seta="ETDP SETA",
         riasec=dict(R=0.2, I=0.3, A=0.4, S=0.9, E=0.3, C=0.4),
         personality=dict(openness=0.5, conscientiousness=0.8, extraversion=0.65, agreeableness=0.85, neuroticism=0.2),
         subjects={"Mathematics": 45, "English": 55},
         min_aps=22, duration_years=4, budget_level=1, salary_entry=220000, growth_outlook="High",
         description="Teach young learners (Grade R-3) foundational literacy and numeracy.",
         next_steps=["Study a B.Ed Foundation Phase degree",
                      "Apply for the Funza Lushaka teaching bursary"]),
    dict(name="High School Subject Teacher", sector="Education", seta="ETDP SETA",
         riasec=dict(R=0.2, I=0.5, A=0.35, S=0.85, E=0.3, C=0.4),
         personality=dict(openness=0.55, conscientiousness=0.75, extraversion=0.6, agreeableness=0.75, neuroticism=0.25),
         subjects={"Mathematics": 55, "English": 55},
         min_aps=24, duration_years=4, budget_level=1, salary_entry=230000, growth_outlook="High",
         description="Teach a specialised subject (e.g. Maths, Science) at high-school level.",
         next_steps=["Study a B.Ed with your subject specialisation",
                      "Apply for the Funza Lushaka bursary, especially for Maths/Science"]),
    dict(name="Social Worker", sector="Social Services", seta="HWSETA",
         riasec=dict(R=0.15, I=0.4, A=0.2, S=0.95, E=0.3, C=0.4),
         personality=dict(openness=0.5, conscientiousness=0.7, extraversion=0.55, agreeableness=0.9, neuroticism=0.25),
         subjects={"English": 55},
         min_aps=22, duration_years=4, budget_level=1, salary_entry=210000, growth_outlook="High",
         description="Support vulnerable individuals and families through counselling and case work.",
         next_steps=["Study a BSW (Bachelor of Social Work)",
                      "Register with the SACSSP after graduating"]),
    dict(name="Psychologist (Counselling)", sector="Social Services", seta="HWSETA",
         riasec=dict(R=0.1, I=0.7, A=0.3, S=0.9, E=0.3, C=0.35),
         personality=dict(openness=0.6, conscientiousness=0.75, extraversion=0.5, agreeableness=0.85, neuroticism=0.2),
         subjects={"Mathematics": 50, "English": 60, "Life Sciences": 50},
         min_aps=30, duration_years=6, budget_level=3, salary_entry=260000, growth_outlook="Medium",
         description="Assess and support mental health and wellbeing (requires honours + masters).",
         next_steps=["Study BA/BSocSci Psychology, then honours and masters",
                      "Register with the HPCSA as an intern psychologist"]),
    dict(name="Community Development Worker", sector="Social Services", seta="LGSETA",
         riasec=dict(R=0.3, I=0.35, A=0.2, S=0.9, E=0.4, C=0.35),
         personality=dict(openness=0.5, conscientiousness=0.65, extraversion=0.6, agreeableness=0.85, neuroticism=0.25),
         subjects={"English": 50},
         min_aps=16, duration_years=2, budget_level=1, salary_entry=160000, growth_outlook="Medium",
         description="Coordinate community upliftment programmes in health, education or welfare.",
         next_steps=["Study a Diploma/Certificate in Community Development",
                      "Volunteer with local NGOs to build experience"]),
    dict(name="Paralegal / Legal Assistant", sector="Legal", seta="Services SETA",
         riasec=dict(R=0.15, I=0.6, A=0.2, S=0.4, E=0.4, C=0.75),
         personality=dict(openness=0.45, conscientiousness=0.85, extraversion=0.4, agreeableness=0.5, neuroticism=0.25),
         subjects={"English": 60},
         min_aps=20, duration_years=2, budget_level=1, salary_entry=180000, growth_outlook="Medium",
         description="Support attorneys with research, documentation and case preparation.",
         next_steps=["Study a Paralegal Diploma or LLB (for attorney route)"]),
    dict(name="Attorney / Lawyer", sector="Legal", seta="Services SETA",
         riasec=dict(R=0.1, I=0.65, A=0.2, S=0.5, E=0.6, C=0.6),
         personality=dict(openness=0.5, conscientiousness=0.85, extraversion=0.55, agreeableness=0.5, neuroticism=0.25),
         subjects={"English": 65},
         min_aps=32, duration_years=4, budget_level=2, salary_entry=280000, growth_outlook="Medium",
         description="Advise and represent clients on legal matters.",
         next_steps=["Study an LLB degree", "Complete articles of clerkship and board exams to become an attorney"]),
    dict(name="Police Officer", sector="Public Safety", seta="Services SETA",
         riasec=dict(R=0.7, I=0.35, A=0.1, S=0.6, E=0.4, C=0.4),
         personality=dict(openness=0.35, conscientiousness=0.75, extraversion=0.55, agreeableness=0.55, neuroticism=0.2),
         subjects={"English": 45},
         min_aps=16, duration_years=1, budget_level=1, salary_entry=190000, growth_outlook="Medium",
         description="Enforce the law and protect communities.",
         next_steps=["Apply directly to SAPS recruitment", "Pass fitness, psychometric and background checks"]),

    # ---------------- CREATIVE & MEDIA ----------------
    dict(name="Graphic Designer", sector="Creative", seta="MICT SETA",
         riasec=dict(R=0.2, I=0.3, A=0.9, S=0.2, E=0.4, C=0.35),
         personality=dict(openness=0.85, conscientiousness=0.55, extraversion=0.4, agreeableness=0.45, neuroticism=0.3),
         subjects={"English": 50},
         min_aps=18, duration_years=3, budget_level=2, salary_entry=180000, growth_outlook="Medium",
         description="Create visual concepts for branding, media and digital products.",
         next_steps=["Study a Diploma/Degree in Graphic Design",
                      "Build a portfolio on Behance and freelance early"]),
    dict(name="Film & TV Production", sector="Creative", seta="MICT SETA",
         riasec=dict(R=0.4, I=0.3, A=0.9, S=0.4, E=0.5, C=0.25),
         personality=dict(openness=0.85, conscientiousness=0.55, extraversion=0.55, agreeableness=0.45, neuroticism=0.3),
         subjects={"English": 50},
         min_aps=18, duration_years=3, budget_level=2, salary_entry=170000, growth_outlook="Medium",
         description="Plan and produce film, television or digital video content.",
         next_steps=["Study Film & Media Production", "Gain experience on student/community productions"]),
    dict(name="Journalist / Media Writer", sector="Creative", seta="MICT SETA",
         riasec=dict(R=0.15, I=0.55, A=0.7, S=0.5, E=0.45, C=0.35),
         personality=dict(openness=0.75, conscientiousness=0.6, extraversion=0.55, agreeableness=0.45, neuroticism=0.3),
         subjects={"English": 65},
         min_aps=22, duration_years=3, budget_level=2, salary_entry=190000, growth_outlook="Low",
         description="Research and write news or feature content across media platforms.",
         next_steps=["Study Journalism/Media Studies", "Start a blog or student publication to build a portfolio"]),
    dict(name="Musician / Sound Engineer", sector="Creative", seta="MICT SETA",
         riasec=dict(R=0.3, I=0.3, A=0.9, S=0.3, E=0.4, C=0.2),
         personality=dict(openness=0.85, conscientiousness=0.5, extraversion=0.55, agreeableness=0.45, neuroticism=0.3),
         subjects={"English": 45},
         min_aps=16, duration_years=2, budget_level=1, salary_entry=140000, growth_outlook="Low",
         description="Compose, perform or engineer music and audio.",
         next_steps=["Study a Diploma in Music Technology/Performance", "Build an online portfolio/demo reel"]),
    dict(name="Fashion Designer", sector="Creative", seta="CTFL SETA",
         riasec=dict(R=0.4, I=0.25, A=0.9, S=0.3, E=0.5, C=0.3),
         personality=dict(openness=0.85, conscientiousness=0.6, extraversion=0.45, agreeableness=0.45, neuroticism=0.3),
         subjects={"English": 45},
         min_aps=16, duration_years=3, budget_level=2, salary_entry=150000, growth_outlook="Low",
         description="Design clothing and accessories for retail or bespoke markets.",
         next_steps=["Study Fashion Design at a university of technology",
                      "Enter local design competitions to build a name"]),
    dict(name="Architect", sector="Creative/Engineering", seta="CETA",
         riasec=dict(R=0.5, I=0.6, A=0.85, S=0.2, E=0.4, C=0.4),
         personality=dict(openness=0.8, conscientiousness=0.75, extraversion=0.35, agreeableness=0.4, neuroticism=0.25),
         subjects={"Mathematics": 60, "Physical Sciences": 50, "English": 55},
         min_aps=32, duration_years=6, budget_level=3, salary_entry=250000, growth_outlook="Medium",
         description="Design buildings and spaces balancing form, function and safety.",
         next_steps=["Push Maths above 60% and build a design portfolio",
                      "Study BAS/BArch and register with SACAP"]),

    # ---------------- AGRICULTURE, ENVIRONMENT & SCIENCE ----------------
    dict(name="Agricultural Scientist / Agronomist", sector="Agriculture", seta="AgriSETA",
         riasec=dict(R=0.6, I=0.85, A=0.15, S=0.3, E=0.3, C=0.4),
         personality=dict(openness=0.6, conscientiousness=0.75, extraversion=0.35, agreeableness=0.5, neuroticism=0.25),
         subjects={"Mathematics": 55, "Physical Sciences": 55, "Life Sciences": 65},
         min_aps=26, duration_years=4, budget_level=2, salary_entry=230000, growth_outlook="Medium",
         description="Research and improve crop/livestock production and sustainability.",
         next_steps=["Keep Life Sciences above 60%", "Study BSc Agriculture at UP, UFS, Stellenbosch"]),
    dict(name="Farm Manager", sector="Agriculture", seta="AgriSETA",
         riasec=dict(R=0.8, I=0.5, A=0.1, S=0.3, E=0.5, C=0.4),
         personality=dict(openness=0.45, conscientiousness=0.75, extraversion=0.45, agreeableness=0.5, neuroticism=0.25),
         subjects={"Mathematics": 45, "Life Sciences": 50},
         min_aps=18, duration_years=2, budget_level=1, salary_entry=180000, growth_outlook="Medium",
         description="Manage day-to-day farm operations, staff and production.",
         next_steps=["Study a Diploma in Agricultural Management",
                      "Look at AgriSETA learnerships and Land Bank youth programmes"]),
    dict(name="Environmental Scientist", sector="Environment", seta="EWSETA",
         riasec=dict(R=0.5, I=0.9, A=0.2, S=0.4, E=0.25, C=0.4),
         personality=dict(openness=0.65, conscientiousness=0.75, extraversion=0.35, agreeableness=0.55, neuroticism=0.25),
         subjects={"Mathematics": 55, "Physical Sciences": 60, "Life Sciences": 60},
         min_aps=28, duration_years=4, budget_level=2, salary_entry=230000, growth_outlook="High",
         description="Study and help protect ecosystems, water and air quality.",
         next_steps=["Study BSc Environmental Science", "Volunteer with conservation NGOs for experience"]),
    dict(name="Geologist / Mining Engineer", sector="Mining", seta="MQA",
         riasec=dict(R=0.75, I=0.85, A=0.1, S=0.2, E=0.35, C=0.4),
         personality=dict(openness=0.55, conscientiousness=0.75, extraversion=0.3, agreeableness=0.4, neuroticism=0.25),
         subjects={"Mathematics": 65, "Physical Sciences": 65},
         min_aps=30, duration_years=4, budget_level=3, salary_entry=350000, growth_outlook="Medium",
         description="Locate and extract mineral resources safely and sustainably.",
         next_steps=["Push Maths and Physical Sciences above 65%",
                      "Study BSc Geology or BEng Mining Engineering; look at MQA bursaries"]),
    dict(name="Veterinarian", sector="Health/Agriculture", seta="AgriSETA",
         riasec=dict(R=0.5, I=0.9, A=0.15, S=0.6, E=0.25, C=0.4),
         personality=dict(openness=0.55, conscientiousness=0.85, extraversion=0.4, agreeableness=0.7, neuroticism=0.2),
         subjects={"Mathematics": 65, "Physical Sciences": 65, "Life Sciences": 70},
         min_aps=36, duration_years=6, budget_level=3, salary_entry=280000, growth_outlook="Medium",
         description="Diagnose and treat animal health conditions.",
         next_steps=["Target 65-70% in the sciences", "Apply to the BVSc at the University of Pretoria (only SA option)"]),

    # ---------------- HOSPITALITY & TOURISM ----------------
    dict(name="Chef / Culinary Professional", sector="Hospitality", seta="CATHSSETA",
         riasec=dict(R=0.6, I=0.3, A=0.6, S=0.4, E=0.4, C=0.35),
         personality=dict(openness=0.6, conscientiousness=0.7, extraversion=0.5, agreeableness=0.5, neuroticism=0.3),
         subjects={"English": 45},
         min_aps=16, duration_years=2, budget_level=1, salary_entry=150000, growth_outlook="Medium",
         description="Prepare and manage food production in restaurants or hotels.",
         next_steps=["Study a Diploma in Culinary Arts (or via chef schools like Capsicum)",
                      "Look at CATHSSETA learnerships and hotel apprenticeships"]),
    dict(name="Tourism / Hospitality Manager", sector="Hospitality", seta="CATHSSETA",
         riasec=dict(R=0.3, I=0.3, A=0.35, S=0.7, E=0.65, C=0.4),
         personality=dict(openness=0.6, conscientiousness=0.7, extraversion=0.75, agreeableness=0.65, neuroticism=0.25),
         subjects={"English": 55, "Geography": 45},
         min_aps=20, duration_years=3, budget_level=2, salary_entry=170000, growth_outlook="Medium",
         description="Manage hotels, lodges or tourism operations and guest experience.",
         next_steps=["Study a Diploma in Hospitality/Tourism Management",
                      "Gain experience through internships at hotels/lodges"]),
    dict(name="Pilot (Commercial Aviation)", sector="Aviation", seta="TETA",
         riasec=dict(R=0.75, I=0.7, A=0.1, S=0.2, E=0.4, C=0.55),
         personality=dict(openness=0.5, conscientiousness=0.9, extraversion=0.4, agreeableness=0.4, neuroticism=0.15),
         subjects={"Mathematics": 60, "Physical Sciences": 60, "English": 55},
         min_aps=28, duration_years=2, budget_level=3, salary_entry=300000, growth_outlook="Medium",
         description="Fly commercial aircraft; requires a pilot's licence and hours-building.",
         next_steps=["Keep Maths/Physical Sciences above 60%",
                      "Research SAA/CAA-approved flight schools and cadet bursary programmes"]),

    # ---------------- SPORTS & OTHER ----------------
    dict(name="Sports Coach / Biokineticist", sector="Sport & Recreation", seta="SASSETA/HWSETA",
         riasec=dict(R=0.6, I=0.5, A=0.2, S=0.75, E=0.4, C=0.3),
         personality=dict(openness=0.5, conscientiousness=0.7, extraversion=0.65, agreeableness=0.6, neuroticism=0.25),
         subjects={"Life Sciences": 55, "English": 50},
         min_aps=22, duration_years=4, budget_level=2, salary_entry=200000, growth_outlook="Medium",
         description="Train athletes or help patients recover through structured exercise.",
         next_steps=["Study Sport Science / Biokinetics",
                      "Volunteer coaching school/community sport for experience"]),
    dict(name="Artisan Welder / Boilermaker", sector="Trades", seta="merSETA",
         riasec=dict(R=0.9, I=0.35, A=0.15, S=0.15, E=0.2, C=0.35),
         personality=dict(openness=0.3, conscientiousness=0.7, extraversion=0.3, agreeableness=0.45, neuroticism=0.2),
         subjects={"Mathematics": 40},
         min_aps=14, duration_years=3, budget_level=1, salary_entry=160000, growth_outlook="Medium",
         description="Join and fabricate metal structures as a qualified trade.",
         next_steps=["Enrol in a TVET welding programme or apprenticeship", "Complete a merSETA trade test"]),
    dict(name="Quantity Surveyor", sector="Engineering", seta="CETA",
         riasec=dict(R=0.4, I=0.6, A=0.15, S=0.2, E=0.45, C=0.75),
         personality=dict(openness=0.45, conscientiousness=0.85, extraversion=0.35, agreeableness=0.4, neuroticism=0.2),
         subjects={"Mathematics": 65, "Physical Sciences": 50},
         min_aps=28, duration_years=4, budget_level=2, salary_entry=280000, growth_outlook="Medium",
         description="Manage construction costs, budgets and contracts.",
         next_steps=["Push Maths above 65%", "Study BSc Quantity Surveying and register with SACQSP"]),
    dict(name="Town/Urban Planner", sector="Public Sector", seta="LGSETA",
         riasec=dict(R=0.3, I=0.65, A=0.35, S=0.4, E=0.35, C=0.55),
         personality=dict(openness=0.6, conscientiousness=0.75, extraversion=0.4, agreeableness=0.5, neuroticism=0.25),
         subjects={"Mathematics": 55, "Geography": 55},
         min_aps=26, duration_years=4, budget_level=2, salary_entry=230000, growth_outlook="Medium",
         description="Plan land use and urban development for municipalities.",
         next_steps=["Study BSc/BA Town and Regional Planning", "Register with SACPLAN"]),
    dict(name="Occupational Therapist", sector="Health", seta="HWSETA",
         riasec=dict(R=0.4, I=0.6, A=0.35, S=0.85, E=0.2, C=0.35),
         personality=dict(openness=0.55, conscientiousness=0.8, extraversion=0.55, agreeableness=0.8, neuroticism=0.2),
         subjects={"Mathematics": 55, "Physical Sciences": 50, "Life Sciences": 60},
         min_aps=30, duration_years=4, budget_level=3, salary_entry=270000, growth_outlook="Medium",
         description="Help people regain independence in daily activities after illness/injury.",
         next_steps=["Keep Life Sciences above 55%", "Apply to Wits, UCT, UP, UWC, UFS OT programmes"]),
    dict(name="Radiographer", sector="Health", seta="HWSETA",
         riasec=dict(R=0.5, I=0.7, A=0.15, S=0.65, E=0.2, C=0.5),
         personality=dict(openness=0.45, conscientiousness=0.8, extraversion=0.45, agreeableness=0.65, neuroticism=0.2),
         subjects={"Mathematics": 55, "Physical Sciences": 60, "Life Sciences": 55},
         min_aps=28, duration_years=4, budget_level=2, salary_entry=260000, growth_outlook="Medium",
         description="Operate imaging equipment (X-ray, CT, MRI) to diagnose conditions.",
         next_steps=["Keep Physical Sciences above 55%", "Apply to Diagnostic Radiography programmes"]),
    dict(name="Biotechnologist", sector="Science", seta="AgriSETA/HWSETA",
         riasec=dict(R=0.4, I=0.9, A=0.2, S=0.3, E=0.3, C=0.5),
         personality=dict(openness=0.65, conscientiousness=0.8, extraversion=0.3, agreeableness=0.45, neuroticism=0.25),
         subjects={"Mathematics": 60, "Physical Sciences": 60, "Life Sciences": 65},
         min_aps=28, duration_years=4, budget_level=2, salary_entry=240000, growth_outlook="Medium",
         description="Apply biology and technology to develop products in medicine, agriculture and industry.",
         next_steps=["Keep Life Sciences above 60%", "Study BSc Biotechnology/Microbiology"]),
    dict(name="Bricklayer / Construction Supervisor", sector="Trades", seta="CETA",
         riasec=dict(R=0.85, I=0.3, A=0.15, S=0.25, E=0.35, C=0.35),
         personality=dict(openness=0.3, conscientiousness=0.7, extraversion=0.4, agreeableness=0.5, neuroticism=0.25),
         subjects={"Mathematics": 40},
         min_aps=14, duration_years=2, budget_level=1, salary_entry=140000, growth_outlook="Medium",
         description="Build structures and supervise construction site teams.",
         next_steps=["Enrol in a TVET construction programme or on-site apprenticeship",
                      "Complete a CETA-recognised trade qualification"]),
]

RIASEC_KEYS = ["R", "I", "A", "S", "E", "C"]
BIG5_KEYS = ["openness", "conscientiousness", "extraversion", "agreeableness", "neuroticism"]

ALL_SUBJECTS = sorted({s for c in CAREERS for s in c["subjects"].keys()} |
                       {"Mathematics", "Physical Sciences", "Life Sciences", "Accounting",
                        "Business Studies", "Economics", "English", "Geography", "History"})

if __name__ == "__main__":
    print(f"{len(CAREERS)} careers loaded across {len(set(c['sector'] for c in CAREERS))} sectors")
